In [1]:
import numpy as np
import pandas as pd
import plotly.express as px
import plotly.graph_objects as go

df = pd.read_csv('ipl_2026.csv')
df.head()

,match_id,date,venue,team1,team2,stage,toss_winner,toss_decision,first_ings_score,first_ings_wkts,second_ings_score,second_ings_wkts,match_winner,won_by,margin,player_of_the_match,top_scorer,highscore,best_bowling,best_bowling_figure
0,1,2026-03-28,"M Chinnaswamy Stadium, Bengaluru",Sunrisers Hyderabad,Royal Challengers Bengaluru,Group,Sunrisers Hyderabad,field,201,9,203,4,Royal Challengers Bengaluru,Wickets,6,JA Duffy,Phil Salt,90.0,Bhuvneshwar Kumar,5/37
1,2,2026-03-29,"Wankhede Stadium, Mumbai",Kolkata Knight Riders,Mumbai Indians,Group,Mumbai Indians,field,220,4,224,4,Mumbai Indians,Wickets,6,SN Thakur,Ajinkya Rahane,103.0,Varun Chakravarthy,2/26
2,3,2026-03-30,"Barsapara Cricket Stadium, Guwahati",Chennai Super Kings,Rajasthan Royals,Group,Chennai Super Kings,field,127,10,128,2,Rajasthan Royals,Wickets,8,N Burger,Riyan Parag,51.0,Noor Ahmad,4/37
3,4,2026-03-31,Maharaja Yadavindra Singh International Cricke...,Gujarat Titans,Punjab Kings,Group,Punjab Kings,bat,162,6,165,7,Punjab Kings,Wickets,3,C Connolly,Nehal Wadhera,36.0,Mohammed Siraj,4/26
4,5,2026-04-01,Bharat Ratna Shri Atal Bihari Vajpayee Ekana C...,Lucknow Super Giants,Delhi Capitals,Group,Lucknow Super Giants,field,141,10,145,4,Delhi Capitals,Wickets,6,Sameer Rizvi,Ravi Bishnoi,115.0,Mitchell Starc,5/14

In [2]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 74 entries, 0 to 73
Data columns (total 20 columns):
 #   Column               Non-Null Count  Dtype
---  ------               --------------  -----
 0   match_id             74 non-null     int64
 1   date                 74 non-null     str
 2   venue                74 non-null     str
 3   team1                74 non-null     str
 4   team2                74 non-null     str
 5   stage                74 non-null     str
 6   toss_winner          74 non-null     str
 7   toss_decision        74 non-null     str
 8   first_ings_score     74 non-null     int64
 9   first_ings_wkts      74 non-null     int64
 10  second_ings_score    74 non-null     int64
 11  second_ings_wkts     74 non-null     int64
 12  match_winner         74 non-null     str
 13  won_by               74 non-null     str
 14  margin               74 non-null     int64
 15  player_of_the_match  74 non-null     str
 16  top_scorer           74 non-null     str
 17  highscore            74 non-null     float64
 18  best_bowling         74 non-null     str
 19  best_bowling_figure  74 non-null     str
dtypes: float64(1), int64(6), str(13)
memory usage: 11.7 KB

1) Which team won the most matches?

In [3]:
match_wins = df['match_winner'].value_counts()
fig = px.bar(x=match_wins.values, y=match_wins.index, orientation='h',
             color=match_wins.index, color_discrete_sequence=px.colors.sequential.Viridis,
             labels={'x': 'Matches Won', 'y': 'Team'},
             title='Most match win by teams')
fig.update_layout(yaxis={'categoryorder': 'total ascending'}, showlegend=False)
fig.show()

2) Toss Decision Trends?

In [4]:
toss_counts = df['toss_decision'].value_counts()
fig = px.bar(x=toss_counts.index, y=toss_counts.values,
             color=toss_counts.index, color_discrete_sequence=px.colors.qualitative.Set2,
             labels={'x': 'Toss Decision', 'y': 'Count'},
             title='Toss Decision Trends')
fig.update_layout(showlegend=False)
fig.show()

3) Toss Winner vs Match Winner

In [5]:
count = df[df['toss_winner'] == df['match_winner']]['match_id'].count()
percentage = (count * 100)/df.shape[0]
percentage.round(2)

np.float64(40.54)

4) How do teams win? (Runs vs Wicket)

In [6]:
won_by_counts = df['won_by'].value_counts()
fig = px.bar(x=won_by_counts.index, y=won_by_counts.values,
             color=won_by_counts.index, color_discrete_sequence=px.colors.qualitative.Set1,
             labels={'x': 'Won By', 'y': 'Count'},
             title='Won by')
fig.update_layout(showlegend=False)
fig.show()

   Key Player Performances

1) Most "Players of the Match" Awards

In [7]:
count = df['player_of_the_match'].value_counts().head(10)
count

player_of_the_match
V Suryavanshi    3
SV Samson        3
V Kohli          3
Ishan Kishan     3
Sameer Rizvi     2
Priyansh Arya    2
Rashid Khan      2
SS Iyer          2
JR Hazlewood     2
Shubman Gill     2
Name: count, dtype: int64

In [8]:
fig = px.bar(x=count.values, y=count.index, orientation='h',
             color=count.index, color_discrete_sequence=px.colors.sequential.Magma,
             labels={'x': 'Awards', 'y': 'Player'},
             title='Top 10 Players with the of the match')
fig.update_layout(yaxis={'categoryorder': 'total ascending'}, showlegend=False)
fig.show()

2) Top Sorers

In [9]:
high = df.groupby('top_scorer')['highscore'].sum().sort_values(ascending=False).head(2)
high

top_scorer
Phil Salt      320.0
Trent Boult    302.0
Name: highscore, dtype: float64

In [10]:
fig = px.bar(x=high.values, y=high.index, orientation='h',
             labels={'x': 'Highscore', 'y': 'Top Scorer'})
fig.update_layout(yaxis={'categoryorder': 'total ascending'})
fig.show()

3) 10 Best Bowling Figures

In [11]:
df['highest_wickets'] = df['best_bowling_figure'].apply(lambda x: x.split('/')[0])
df['highest_wickets'] = df['highest_wickets'].astype(int)

top_bowler = df.groupby('best_bowling')['highest_wickets'].sum().sort_values(ascending=False).head(10)
fig = px.bar(x=top_bowler.values, y=top_bowler.index, orientation='h',
             labels={'x': 'Total Wickets', 'y': 'Bowler'},
             title='10 Best Bowling Figures')
fig.update_layout(yaxis={'categoryorder': 'total ascending'})
fig.show()

   Venue Analysis

Most Matches Played by Venue

In [12]:
venue_count = df['venue'].value_counts()
venue_count

venue
Narendra Modi Stadium, Ahmedabad                                           8
Wankhede Stadium, Mumbai                                                   7
Bharat Ratna Shri Atal Bihari Vajpayee Ekana Cricket Stadium, Lucknow      7
Eden Gardens, Kolkata                                                      7
MA Chidambaram Stadium, Chepauk, Chennai                                   7
Arun Jaitley Stadium, Delhi                                                7
Rajiv Gandhi International Stadium, Uppal, Hyderabad                       7
Maharaja Yadavindra Singh International Cricket Stadium, New Chandigarh    6
M Chinnaswamy Stadium, Bengaluru                                           5
Sawai Mansingh Stadium, Jaipur                                             4
Himachal Pradesh Cricket Association Stadium, Dharamsala                   4
Barsapara Cricket Stadium, Guwahati                                        3
Shaheed Veer Narayan Singh International Stadium, Raipur                   2
Name: count, dtype: int64

In [13]:
fig = px.bar(y=venue_count.index, x=venue_count.values, orientation='h',
             color=venue_count.index, color_discrete_sequence=px.colors.qualitative.Prism,
             labels={'x': 'Matches Played', 'y': 'Venue'},
             title='Most Matches Played by Venue')
fig.update_layout(yaxis={'categoryorder': 'total ascending'}, showlegend=False)
fig.show()

    Insights

1) Who won the highest margin by runs ?

In [14]:
df[df['won_by'] == 'Runs'].sort_values(by='margin', ascending=False).head(1)[['match_winner', 'margin']]

           match_winner  margin
32  Chennai Super Kings     103

2) Which player had the highest individual score

In [15]:
df[df['highscore'] == df['highscore'].max()][['top_scorer', 'highscore']]

      top_scorer  highscore
8  Sai Sudharsan      133.0

3) Which Bowler had the best bowling figure?

In [16]:
df[df['highest_wickets'] == df['highest_wickets'].max()][['best_bowling', 'best_bowling_figure']]

          best_bowling best_bowling_figure
0    Bhuvneshwar Kumar                5/37
4       Mitchell Starc                5/14
5   Varun Chakravarthy                5/24
7       Mitchell Starc                5/27
8         Jofra Archer                5/33
9         Ravi Bishnoi                5/37
11      Arshdeep Singh                5/37
12      Jasprit Bumrah                5/34
22        Ravi Bishnoi                5/13
26          Noor Ahmad                5/17
35        Jofra Archer                5/25
37          Noor Ahmad                5/22
44         Rashid Khan                5/34
57      Jasprit Bumrah                5/36
60       Kuldeep Yadav                5/35
61   Bhuvneshwar Kumar                5/20
62          Noor Ahmad                5/32
71      Mohammed Shami                5/16
73         Rashid Khan                5/31